// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTCGLottoLibrary.Models.CodeFirsts;

namespace PTCGLottoBackend.Migrations
{
    [DbContext(typeof(PTCGLottoContext))]
    [Migration("20190802091907_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardTypeId");

                    b.Property<int>("ExpansionId");

                    b.Property<string>("Name");

                    b.Property<int>("No");

                    b.Property<int>("RarityId");

                    b.HasKey("Id");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("ExpansionId");

                    b.HasIndex("RarityId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Pheromosa & Buzzwole-GX",
                            No = 1,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 2,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Caterpie",
                            No = 2,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 3,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Metapod",
                            No = 3,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 4,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Butterfree",
                            No = 4,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 5,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Oddish",
                            No = 5,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 6,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Oddish",
                            No = 6,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 7,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gloom",
                            No = 7,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 8,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Vileplume",
                            No = 8,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 9,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Venonat",
                            No = 9,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 10,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Venonat",
                            No = 10,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 11,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Venomoth",
                            No = 11,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 12,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Venomoth-GX",
                            No = 12,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 13,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Bellsprout",
                            No = 13,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 14,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Weepinbell",
                            No = 14,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 15,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Victreebel",
                            No = 15,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 16,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Tangela",
                            No = 16,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 17,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Tangrowth",
                            No = 17,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 18,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Grubbin",
                            No = 18,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 19,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Kartana",
                            No = 19,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 20,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Reshiram & Charizard-GX",
                            No = 20,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 21,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Growlithe",
                            No = 21,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 22,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Arcanine",
                            No = 22,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 23,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Darumaka",
                            No = 23,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 24,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Darmanitan",
                            No = 24,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 25,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Volcanion",
                            No = 25,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 26,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Litten",
                            No = 26,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 27,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Litten",
                            No = 27,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 28,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Torracat",
                            No = 28,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 29,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Incineroar",
                            No = 29,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 30,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Salandit",
                            No = 30,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 31,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Salazzle",
                            No = 31,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 32,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Blacephalon",
                            No = 32,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 33,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Squirtle",
                            No = 33,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 34,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Wartortle",
                            No = 34,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 35,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Blastoise-GX",
                            No = 35,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 36,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Poliwag",
                            No = 36,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 37,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Poliwag",
                            No = 37,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 38,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Poliwhirl",
                            No = 38,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 39,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Poliwrath",
                            No = 39,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 40,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Tentacool",
                            No = 40,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 41,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Tentacruel",
                            No = 41,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 42,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Slowpoke",
                            No = 42,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 43,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Slowbro",
                            No = 43,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 44,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Seel",
                            No = 44,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 45,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Dewgong",
                            No = 45,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 46,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Krabby",
                            No = 46,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 47,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Kingler",
                            No = 47,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 48,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Goldeen",
                            No = 48,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 49,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Seaking",
                            No = 49,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 50,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Kyurem",
                            No = 50,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 51,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Froakie",
                            No = 51,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 52,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Frogadier",
                            No = 52,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 53,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Pyukumuku",
                            No = 53,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 54,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Pikachu",
                            No = 54,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 55,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Raichu",
                            No = 55,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 56,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Stunfisk",
                            No = 56,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 57,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Dedenne-GX",
                            No = 57,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 58,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Charjabug",
                            No = 58,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 59,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Vikavolt",
                            No = 59,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 60,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Zeraora",
                            No = 60,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 61,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Muk & Alolan Muk-GX",
                            No = 61,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 62,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Ekans",
                            No = 62,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 63,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Arbok",
                            No = 63,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 64,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Zubat",
                            No = 64,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 65,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Golbat",
                            No = 65,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 66,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Crobat",
                            No = 66,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 67,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gastly",
                            No = 67,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 68,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gastly",
                            No = 68,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 69,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Haunter",
                            No = 69,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 70,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gengar",
                            No = 70,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 71,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Drowzee",
                            No = 71,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 72,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Hypno",
                            No = 72,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 73,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Koffing",
                            No = 73,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 74,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Weezing",
                            No = 74,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 75,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Mewtwo",
                            No = 75,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 76,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Mew",
                            No = 76,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 77,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Misdreavus",
                            No = 77,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 78,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Mismagius",
                            No = 78,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 79,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Espurr",
                            No = 79,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 80,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Meowstic",
                            No = 80,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 81,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Marshadow",
                            No = 81,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 82,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Marshadow & Machamp-GX",
                            No = 82,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 83,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Sandshrew",
                            No = 83,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 84,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Sandslash",
                            No = 84,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 85,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Diglett",
                            No = 85,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 86,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Dugtrio",
                            No = 86,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 87,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Geodude",
                            No = 87,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 88,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Graveler",
                            No = 88,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 89,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Golem",
                            No = 89,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 90,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Cubone",
                            No = 90,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 91,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Marowak",
                            No = 91,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 92,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Rhyhorn",
                            No = 92,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 93,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Rhyhorn",
                            No = 93,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 94,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Rhydon",
                            No = 94,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 95,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Rhyperior",
                            No = 95,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 96,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Wooper",
                            No = 96,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 97,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Quagsire",
                            No = 97,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 98,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gligar",
                            No = 98,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 99,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gliscor",
                            No = 99,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 100,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Tyrogue",
                            No = 100,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 101,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Hitmontop",
                            No = 101,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 102,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Riolu",
                            No = 102,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 103,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Landorus",
                            No = 103,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 104,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Crabrawler",
                            No = 104,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 105,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Crabominable",
                            No = 105,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 106,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Stakataka",
                            No = 106,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 107,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Greninja & Zoroark-GX",
                            No = 107,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 108,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Murkrow",
                            No = 108,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 109,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Honchkrow-GX",
                            No = 109,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 110,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Carvanha",
                            No = 110,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 111,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Sharpedo",
                            No = 111,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 112,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Spiritomb",
                            No = 112,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 113,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Sandile",
                            No = 113,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 114,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Sandile",
                            No = 114,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 115,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Krokorok",
                            No = 115,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 116,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Krookodile",
                            No = 116,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 117,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Greninja",
                            No = 117,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 118,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Inkay",
                            No = 118,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 119,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Malamar",
                            No = 119,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 120,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Lucario & Melmetal-GX",
                            No = 120,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 121,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Alolan Diglett",
                            No = 121,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 122,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Alolan Dugtrio",
                            No = 122,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 123,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Aron",
                            No = 123,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 124,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Lairon",
                            No = 124,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 125,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Aggron",
                            No = 125,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 126,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Lucario",
                            No = 126,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 127,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Genesect",
                            No = 127,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 128,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Meltan",
                            No = 128,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 129,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Melmetal",
                            No = 129,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 130,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gardevoir & Sylveon-GX",
                            No = 130,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 131,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Cleffa",
                            No = 131,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 132,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Clefairy",
                            No = 132,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 133,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Clefable",
                            No = 133,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 134,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Jigglypuff",
                            No = 134,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 135,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Wigglytuff",
                            No = 135,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 136,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Togepi",
                            No = 136,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 137,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Togetic",
                            No = 137,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 138,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Togekiss",
                            No = 138,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 139,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Cottonee",
                            No = 139,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 140,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Whimsicott-GX",
                            No = 140,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 141,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Spritzee",
                            No = 141,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 142,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Aromatisse",
                            No = 142,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 143,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Rattata",
                            No = 143,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 144,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Raticate",
                            No = 144,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 145,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Spearow",
                            No = 145,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 146,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Fearow",
                            No = 146,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 147,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Meowth",
                            No = 147,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 148,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Persian",
                            No = 148,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 149,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Persian-GX",
                            No = 149,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 150,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Doduo",
                            No = 150,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 151,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Dodrio",
                            No = 151,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 152,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Lickitung",
                            No = 152,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 153,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Lickilicky",
                            No = 153,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 154,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Porygon",
                            No = 154,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 155,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Porygon",
                            No = 155,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 156,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Porygon2",
                            No = 156,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 157,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Porygon-Z",
                            No = 157,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 158,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Snorlax",
                            No = 158,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 159,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Glameow",
                            No = 159,
                            RarityId = 1
                        },
                        new
                        {
                            Id = 160,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Purugly",
                            No = 160,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 161,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Happiny",
                            No = 161,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 162,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Chatot",
                            No = 162,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 163,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Celesteela-GX",
                            No = 163,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 164,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Beast Bringer",
                            No = 164,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 165,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Chip-Chip Ice Axe",
                            No = 165,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 166,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Devolution Spray Z",
                            No = 166,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 167,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Dusk Stone",
                            No = 167,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 168,
                            CardTypeId = 5,
                            ExpansionId = 1,
                            Name = "Dust Island",
                            No = 168,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 169,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Electromagnetic Radar",
                            No = 169,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 170,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Energy Spinner",
                            No = 170,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 171,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Fairy Charm Ability",
                            No = 171,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 172,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Fairy Charm Lightning",
                            No = 172,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 173,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Fire Crystal",
                            No = 173,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 174,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Giovanni's Exile",
                            No = 174,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 175,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Green's Exploration",
                            No = 175,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 176,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Janine",
                            No = 176,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 177,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Koga's Trap",
                            No = 177,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 178,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Lt. Surge's Strategy",
                            No = 178,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 179,
                            CardTypeId = 5,
                            ExpansionId = 1,
                            Name = "Martial Arts Dojo",
                            No = 179,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 180,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Metal Core Barrier",
                            No = 180,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 181,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Molayne",
                            No = 181,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 182,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Pokegear 3.0",
                            No = 182,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 183,
                            CardTypeId = 5,
                            ExpansionId = 1,
                            Name = "Power Plant",
                            No = 183,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 184,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Red's Challenge",
                            No = 184,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 185,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Samson Oak",
                            No = 185,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 186,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Stealthy Hood",
                            No = 186,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 187,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Surprise Box",
                            No = 187,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 188,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Ultra Forest Kartenvoy",
                            No = 188,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 189,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Welder",
                            No = 189,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 190,
                            CardTypeId = 3,
                            ExpansionId = 1,
                            Name = "Triple Acceleration Energy",
                            No = 190,
                            RarityId = 2
                        },
                        new
                        {
                            Id = 191,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Pheromosa & Buzzwole-GX",
                            No = 191,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 192,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Pheromosa & Buzzwole-GX",
                            No = 192,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 193,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Venomoth-GX",
                            No = 193,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 194,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Reshiram & Charizard-GX",
                            No = 194,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 195,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Dedenne-GX",
                            No = 195,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 196,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Muk & Alolan Muk-GX",
                            No = 196,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 197,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Muk & Alolan Muk-GX",
                            No = 197,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 198,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Marshadow & Machamp-GX",
                            No = 198,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 199,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Marshadow & Machamp-GX",
                            No = 199,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 200,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Greninja & Zoroark-GX",
                            No = 200,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 201,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Greninja & Zoroark-GX",
                            No = 201,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 202,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Honchkrow-GX",
                            No = 202,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 203,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Lucario & Melmetal-GX",
                            No = 203,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 204,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gardevoir & Sylveon-GX",
                            No = 204,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 205,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gardevoir & Sylveon-GX",
                            No = 205,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 206,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Whimsicott-GX",
                            No = 206,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 207,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Persian-GX",
                            No = 207,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 208,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Celesteela-GX",
                            No = 208,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 209,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Green's Exploration",
                            No = 209,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 210,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Janine",
                            No = 210,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 211,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Koga's Trap",
                            No = 211,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 212,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Molayne",
                            No = 212,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 213,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Red's Challenge",
                            No = 213,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 214,
                            CardTypeId = 2,
                            ExpansionId = 1,
                            Name = "Welder",
                            No = 214,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 215,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Pheromosa & Buzzwole-GX",
                            No = 215,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 216,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Venomoth-GX",
                            No = 216,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 217,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Reshiram & Charizard-GX",
                            No = 217,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 218,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Blastoise-GX",
                            No = 218,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 219,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Dedenne-GX",
                            No = 219,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 220,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Muk & Alolan Muk-GX",
                            No = 220,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 221,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Marshadow & Machamp-GX",
                            No = 221,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 222,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Greninja & Zoroark-GX",
                            No = 222,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 223,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Honchkrow-GX",
                            No = 223,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 224,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Lucario & Melmetal-GX",
                            No = 224,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 225,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Gardevoir & Sylveon-GX",
                            No = 225,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 226,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Whimsicott-GX",
                            No = 226,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 227,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Persian-GX",
                            No = 227,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 228,
                            CardTypeId = 1,
                            ExpansionId = 1,
                            Name = "Celesteela-GX",
                            No = 228,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 229,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Beast Bringer",
                            No = 229,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 230,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Electromagnetic Radar",
                            No = 230,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 231,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Fire Crystal",
                            No = 231,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 232,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Metal Core Barrier",
                            No = 232,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 233,
                            CardTypeId = 4,
                            ExpansionId = 1,
                            Name = "Pokegear 3.0",
                            No = 233,
                            RarityId = 3
                        },
                        new
                        {
                            Id = 234,
                            CardTypeId = 3,
                            ExpansionId = 1,
                            Name = "Triple Acceleration Energy",
                            No = 234,
                            RarityId = 3
                        });
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CardTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pokemon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Supporter"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Energy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Item"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stadium"
                        });
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.CoinTradeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("Memo");

                    b.Property<int?>("StatusId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("CoinTradeHistories");
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CardId");

                    b.Property<int>("Count");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.Expansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("SeriesId");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Expansions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Unbroken Bonds",
                            Price = 100,
                            SeriesId = 1
                        });
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.Rarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.ToTable("Rarities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Common",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Uncommon",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rare",
                            Value = 3
                        });
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Serieses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SUN & MOON"
                        });
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<int>("Coin");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.Card", b =>
                {
                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.CardType", "CardType")
                        .WithMany()
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.Expansion", "Expansion")
                        .WithMany()
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.CoinTradeHistory", b =>
                {
                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.Collection", b =>
                {
                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("PTCGLottoLibrary.Models.CodeFirsts.Expansion", b =>
                {
                    b.HasOne("PTCGLottoLibrary.Models.CodeFirsts.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
